# Generated by Django 3.2.4 on 2022-09-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
