# Generated by Django 3.2.4 on 2022-09-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='num_radicado_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de radicado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='num_radicado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de radicado'),
        ),
    ]
