# Generated by Django 3.2.4 on 2022-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220905_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='num_radicado_2',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='num_radicado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de radicado 2'),
        ),
    ]
