# Generated by Django 3.2.4 on 2022-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220905_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='visibilidad',
            field=models.CharField(choices=[('visible', 'visible'), ('oculto', 'oculto')], default='visible', max_length=200, verbose_name='Visibilidad'),
        ),
    ]
